# config.toml

# ───────────────────────────────────────────────────────────────────────────────
# Required Inputs
# ───────────────────────────────────────────────────────────────────────────────
bams        = ["/private/groups/brookslab/gabai/projects/yeastMeth/data/rna/cage/bam/alpha_YPD/DRR524315.sorted.bam", 
                "/private/groups/brookslab/gabai/projects/yeastMeth/data/rna/cage/bam/alpha_YPD/DRR524316.sorted.bam"]
out_dir    = "/private/groups/brookslab/hdheath/projects/peak_calling-CAGE/output/peak_bedfiles"

# ───────────────────────────────────────────────────────────────────────────────
# Optional Inputs
# ───────────────────────────────────────────────────────────────────────────────
chrom     = "chrIV"        # no chromosome filter
dry_run   = false    # set true to test without writing

# ───────────────────────────────────────────────────────────────────────────────
# Peak-calling 
# ───────────────────────────────────────────────────────────────────────────────

# ───────────────────────────────────────────────────────────────────────────────
# Peak-calling 
# ───────────────────────────────────────────────────────────────────────────────

# DBSCAN: require at least 4–8 tags per cluster, cluster tight peaks
run_dbscan           = true
dbscan_eps           = [5, 10, 15]
dbscan_min_samples   = [4, 6, 8]

# HDBSCAN: same logic
run_hdbscan          = true
hdbscan_min_cluster_size = [4, 6, 8]
hdbscan_min_samples      = [1, 2]

# scipy.find_peaks: call any local maximum ≥4–8 reads, separated by ≤5–15 bp
run_find_peaks       = true
peak_height          = [4, 6, 8]
peak_distance        = [5, 10, 15]

# MACS3: sweep q-value, test no-model/shiftsize/extsize
run_macs3            = true
macs3_gsize          = ["hs", "1.2e7"]          # human vs yeast genome sizes
macs3_qvalue         = [0.001, 0.005, 0.01]
macs3_nomodel        = [false]
macs3_shift          = [0, -75, 75]            # center reads, +/- shift
macs3_extsize        = [147, 200]              # fragment extension lengths
macs3_call_summits   = [true, false]

# Sliding‐window: 5–15 bp bins, require ≥4–8 reads in the bin
run_dbscan_sw        = true
sw_bin               = [5, 10, 15]
sw_threshold         = [4, 6, 8]

# CAGEr: bump threshold, distance, and try the "correctFirstG" option
run_cager            = true
cager_threshold      = [4, 6, 8]                # only tags ≥4,6,8
cager_maxdist        = [10, 20, 30]             # cluster within 10,20,30 bp
cager_correctFirstG  = [false, true]            # try correcting first‐G bias
cager_env            = "cager-env"


# ───────────────────────────────────────────────────────────────────────────────
# QC
# ───────────────────────────────────────────────────────────────────────────────
run_qc               = true              # turn on all QC steps
qc_out_dir           = "/private/groups/brookslab/hdheath/projects/peak_calling-CAGE/output/peak_bedfiles/QC"   # where QC outputs go

# 1) Length‐distribution of called regions
#   we’ll glob *.bed under each sample subdirectory

# 2) Long‐read TSS → bed file
long_reads           = [
  "/private/groups/brookslab/gabai/projects/yeastMeth/data/rna/teloprime/tx_alignment/250609_teloprime_ys18_rep1.bam"
]

# 3) Annotation TSS
annotation_bed       = "/private/groups/brookslab/gabai/projects/yeastMeth/data/ref/sacCer3_ares_v13_sorted.bed"

# 4) bedtools environment & distance cutoff 
bedtools_env = "bedtools_env"
qc_dist_cutoff       = 1    # bp threshold for “within x bp”

make_plots= true